// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oncjwspgutrnnsjvadrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9uY2p3c3BndXRybm5zanZhZHJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2OTgxOTQsImV4cCI6MjA2NjI3NDE5NH0.ctW7dyMSlQZkWyX5Pbdt4o1CwiTXuWx5fjyywHhO6c4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);